### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by Matthew19-24** [supersu-man/GitHubAPKUpdater-Library#2]
Hello, I have been trying to add this package to our project and have been running into issues with SSL handshake.

My implementation of your package: When the page is opened, it should check for updates, and if there is an update, it should set the AppName text red for the user to see there are updates. When it is red, it becomes clickable to initiate the download of the update.

Here is the code showing implementation:

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        disableBackPress()
        setScreenOrientation()
        setScannerBindings()
        setupPermissions()
        codeScanner()
        checkForUpdates()
        setOnClickListeners()
    }

private fun checkForUpdates() {
        coroutineScope.launch {
            val updater = ApkUpdater(this@Scanner, "https://github.com/WIGteam/WIG-Android/releases/latest")
            updater.threeNumbers = true
            if (updater.isInternetConnection() && updater.isNewUpdateAvailable() == true) {
                scannerBinding.appName.setTextColor(Color.RED)
                scannerBinding.appName.setOnClickListener { updateButton(updater) }
            }
        }
    }

private fun updateButton(updater: ApkUpdater) {
        updater.requestDownload()
    }
```

Now after adding this feature, the app crashes. I get a stacktrace that seems to mention SSL handshake and trust anchor for certification path not found. I assume Github should have a trusted SSL.

```
FATAL EXCEPTION: main
                                                                                                    Process: wig.wig.android, PID: 12637
                                                                                                    javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                                    	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:896)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:236)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:218)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
                                                                                                    	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
                                                                                                    	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:167)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:227)
                                                                                                    	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderFields(DelegatingHttpsURLConnection.java:179)
                                                                                                    	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderFields(HttpsURLConnectionImpl.java:30)
                                                                                                    	at khttp.responses.GenericResponse$Companion.getCookieJar$library_release(GenericResponse.kt:42)
                                                                                                    	at khttp.responses.GenericResponse$Companion$defaultEndInitializers$3.invoke(GenericResponse.kt:124)
                                                                                                    	at khttp.responses.GenericResponse$Companion$defaultEndInitializers$3.invoke(GenericResponse.kt:39)
                                                                                                    	at khttp.responses.GenericResponse$connection$2.invoke(GenericResponse.kt:173)
                                                                                                    	at khttp.responses.GenericResponse$connection$2.invoke(GenericResponse.kt:37)
                                                                                                    	at khttp.responses.GenericResponse.openRedirectingConnection(GenericResponse.kt:132)
                                                                                                    	at khttp.responses.GenericResponse.getConnection(GenericResponse.kt:171)
                                                                                                    	at khttp.responses.GenericResponse.getRaw(GenericResponse.kt:217)
                                                                                                    	at khttp.responses.GenericResponse.getContent(GenericResponse.kt:226)
                                                                                                    	at khttp.responses.GenericResponse.init$library_release(GenericResponse.kt:385)
                                                                                                    	at khttp.KHttp.request(KHttp.kt:83)
                                                                                                    	at khttp.KHttp.get(KHttp.kt:52)
                                                                                                    	at khttp.KHttp.get$default(KHttp.kt:51)
                                                                                                    	at com.supersuman.apkupdater.ApkUpdater.<init>(Updater.kt:22)
                                                                                                    	at wig.activities.Scanner$checkForUpdates$1.invokeSuspend(Scanner.kt:674)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8762)
2024-03-07 08:20:25.743 12637-12637 AndroidRuntime          wig.wig.android                      E  	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@85086a7, Dispatchers.Main]
                                                                                                    Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:656)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
                                                                                                    	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
                                                                                                    	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
                                                                                                    	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
                                                                                                    	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:260)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
                                                                                                    	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
                                                                                                    	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
                                                                                                    	... 46 more
                                                                                                    Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                                    	... 61 more
```

If you would like to see the full source code or clone the branch [here is the branch link](https://github.com/WIGteam/WIG-Android/tree/51-implement-update-check) - Branch 51-implement-update-check

**Comment by Matthew19-24** [comment]
Edit, made update to issue post. I posted the wrong error the first time.

**Comment by Matthew19-24** [comment]
I fixed the issue in my network_security_config.xml I needed to add <certificates src="system"/>

```
<trust-anchors>
            <certificates src="@raw/cert"/>
            <certificates src="system" />
        </trust-anchors>
```
